### ISSUE TITLE
Issues generating the carrier settings from Android 12 betas

### ISSUE THREAD

**Issue by randomhydrosol** [GrapheneOS/carriersettings-extractor#5]
Testing with android 12 images currently gives the following error:

```~/carriersettings-extractor $ python3 carriersettings_extractor.py CarrierSettings/
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/carriersettings-extractor/carriersettings_extractor.py", line 49, in <module>
    assert setting.canonicalName not in all_settings
AssertionError
```
If the config file that's causing the issue is deleted, this is the error:

``` ~/carriersettings-extractor $ python3 carriersettings_extractor.py CarrierSettings/
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/carriersettings-extractor/carriersettings_extractor.py", line 180, in <module>
    version_suffix = all_settings['default'].version % 1000000000
KeyError: 'default'
~/carriersettings-extractor $
```

**Comment by randomhydrosol** [comment]
It may just be that they forgot to version carrier settings for the beta and will do so in the final release

Reverting b235e1d344d23e4fd5e2303482737d4f2f5212a6 seems to fix it

**Comment by randomhydrosol** [comment]
CC: @flawedworld
